#server:
#  port: ${SERVER_PORT:8081}

kafka-config:
  request-topic: anupam-test-request-topic
  reply-topic: anupam-test-reply-topic
  bootstrap_server: localhost:9092
  group-id: anupam-test
  concurrency: 10
  partitions: 10
  replicas: 2